= Synchronizing Living Colors gen2 and Hue bridge 2.0
:hp-tags: stuff, solution

== The problem

Getting the following lamps:

* Living Colors (LC) and Living Bloom gen2 
* Philips Hue white/color bulbs

All controlled by:
* Living Colors remote(s) gen2 (round remote with the "touch-wheel" for colors)
* Philips bridge v2

There are almost no post on internet about it. Instructions for remote v1 doesn't work with remote v2.



== Solution

. *Plug and turn everything on*

. *Reset the LC remote* +
press the reset button under the battery cover for a few seconds.

. *Reset the Hue Bridge (this will reset your settings)* +
while holding the link button on top of the Hue Bridge, hold the remote close to the Hue Bridge and hold "0" (off) and Blue on colorwheel (-6h) until the Hue Bridge reboots.

. *Associate the LC remote with each Living Colors and Hue bulbs* +
hold the remote close to each item holding the "I" (on) until the item stops blinking. +
_At this point, you can control all items with the remote, but your bridge doesn't detect Living Colors._

. *Associate the LC remote with the Hue bridge* +
press the link button on top of the Hue Bridge and hold the "I" (on) on the remote until the LED around bridge's link button stops blinking.

. *Open Hue app mobile* +
Living Colors and Hue bulbs should be detected! +
_You can now control all lights with the Hue app and the remote._



For adding an additional LC remote:

. *Reset the new remote* +
press the reset button under the battery cover for a few seconds.

. *Associate the remote* +
hold the new remote close to the already configured one and hold the "I" (on) of both remotes until they stop blinking.



---
Sources::

https://www.reddit.com/r/Hue/comments/3wdilk/you_can_connect_gen_2_round_remote_living_colors/ +
https://www.reddit.com/r/Hue/comments/3y0h1s/pair_living_colours_gen2_remote_to_bridge_20/


