= Bitcoin, comment ça marche ?
:hp-tags: bitcoin,blockchain
:hide-uri-scheme:

Cet article décrit le plus succintement possible le fonctionnement de Bitcoin et de la Blockchain.


== Bitcoin en pratique
- comment en obtenir : 

   * en en achetant à quelqu'un qui en vend : sur un exchange (Kraken, Btc-e) ou main en propre (http://localbitcoins.com)

   * en participant à l'effort de création de monnaie par minage (peu rentable, explication ci-dessous)


- pour recevoir des bitcoins il faut une adresse, que vous pouvez créer et gérer avec :
   * un portefeuille _(wallet)_ logiciel : le plus courant, il en existe pour mobile(ex : MyCelium), desktop (ex : Electrum) ou en ligne (http://blockchain.info)
   * d'autres alternatives : adresse à imprimer sur papier (_cold storage_), phrase secrète à mémoriser (_brainwallet_)



== Comprendre son fonctionnement (concepts, sécurité, risques)
=== Qu'est-ce qu'une adresse ?

Pour recevoir des bitcoins il faut une adresse publique (comme une adresse email) se présentant sous la forme _1er7H9CxBQf9Hj6H3kMDCc45ZtPvFfsb7_ ou du QR code correspondant. Cette adresse doit être communiquée pour recevoir un paiement. Tout le monde peut envoyer des bitcoins vers une adresse publique (un commerçant peut imprimer le QR code de son adresse publique sur son comptoir pour recevoir des paiements). +
Chaque adresse publique est associée à une clé privée connue par son seul propriétaire, et qui est requise pour dépenser les bitcoins qui s'y trouvent => cette clé doit rester secrete, c'est la clé du coffre.
    
*Problème : on ne veut pas d'autorité centrale pour générer de nouvelles adresses* +
Solution => tout le monde peut créer des adresses de manière autonome. +
    Pour créer une adresse, on génère une clé privée de 256 bits (32 octets) *à partir de nombres aléatoires sans en informer quiconque*. 
    Par commodité, cette adresse privée peut être représentée sous un format simplifié (51 caractères respectants certains critères avec checksum pour éviter les erreurs). A partir de cette clé privée on déduit l'adresse publique associée (l'opération inverse n'est évidemment pas possible).

Les applications de wallets permettent de générer et stocker des clés privées associées à un ensemble d'adresses publiques et de les mémoriser +
=> risque de bug/perte ou vol de données/piratage/wallet malveillant (ex : un bug RNG _Random Number Generator_ sur android a eu pour conséquence de générer des clés privées affaiblies).

Si on est parano et qu'on n'a pas confiance dans les logiciels :

    - on peut se créer une adresse en jetant des dés avec un peu de patience.
    - des méthodes permettent de dériver des clés privées à partir d'une dizaine de mots d'un dictionnaire => on peut mémoriser ses propres clés si on est parano et qu'on ne veut pas qu'elles aient une existence physique. on peut donc avoir un cerveau qui vaut 3 milliards :)
    
Le réseau n'a donc pas connaissance des adresses "existantes" tant qu'elles ne font pas l'objet d'une transaction. La clé privée ne sera utilisée que pour dépenser des bitcoin, ce qui renforce la sécurité : on peut recevoir des bitcoins sur une adresse sans jamais faire intervenir la clé privée associé.
    
=== Qu'est-ce qu'une transaction ?

Une transaction = adresse source + adresse destination + montant à transférer
    
*Problème : on ne veut pas d'autorité centrale pour générer de nouvelles transactions* +
Solution => tout le monde peut créer des transactions de pair à pair
    
Concrètement on construit un message signé par la clé privée correspondante à l'adresse source (pour prouver qu'on est bien propriétaire des bitcoins à transférer). Tout le monde peut vérifier que la transaction est valide en comparant sa signature avec l'adresse source (= clé publique correspondante à la signature)
    
Une transaction peut être créée offline, imprimée sur papier, et être transmise sur le réseau dans un 2è temps. elle sera toujours valide sous réserve que l'adresse source soit approvisionnée au moment de son exécution.
    (en réalité 1 tx peut avoir n input et n outputs)

*Comment sont traitées les transactions ?* concept de blockchain +
*Problème : on ne veut pas d'autorité centrale pour générer de nouvelles transactions* +
Solution => tout le monde peut traiter les transactions
    
*Problème : pour cela tout le monde doit être en mesure de vérifier la validité des transactions* c à d de vérifier que l'adresse source dispose bien d'un solde de bitcoins suffisant pour les dépenser. +
    Donc tout le monde doit potentiellement connaître le solde de toutes les adresses du réseau. +
    Solution => tout le monde doit pouvoir connaître toutes les transactions depuis l'origine du réseau = le grand livre de compte, registre, ledger, du bitcoin.
    C'est la blockchain. Actuellement cela pèse environ 60Go et ça grossit de quelques Mo chaque heure.
    Pour s'assurer que la transaction est valide, on remonte dans l'historique de toutes les transactions qui ont eu lieu en partant de l'adresse source et ses ancêtres pour s'assurer que l'adresse a bien un solde suffisant.
    
Une fois la transaction validée, elle peut être inscrite dans la blockchain.
    
    
=== Comment fonctionne la blockchain ?

==== En résumé
    
Le réseau Bitcoin repose sur :
        
. des "volontaires" qui font tourner des "full nodes", c'est à dire des noeuds qui enregistrent une copie complète de la blockchain afin d'être en mesure de vérifier la validité des transactions, et de détecter et rejeter les tentatives de fraude sur le réseau.
        Ce travail n'est pas rémunéré. Le nombre de "full nodes" est en baisse (environ 7000) ce qui lève des inquiétudes quant à la décentralisation du réseau.
    

. des "mineurs" qui traitent les transactions, c'est à dire qui les inscrivent dans la blockchain. Pour des raisons techniques, cette opération se fait bloc par bloc toutes les 10 minutes en moyenne, chaque bloc étant limité à 1mo de données (quelques milliers de transactions).
+
Pour ce travail, les mineurs reçoivent :

	1. une récompense pour chaque bloc miné (de 25btc actuellement, divisée par 2 dans quelques mois cf _bitcoin halving_), 
    
    2. ils perçoivent les frais associés aux transactions traitées. Cette opération de minage est très coûteuse en énergie, ce qui garantit la sécurité du réseau (car il serait trop coûteux de falsifier les anciennes transactions comparé aux gains potentiels). 
        => "tout le monde" peut créer de la monnaie (avec de la puissance de calcul et de la chance)
        => Le réseau est rythmé par les "battements de coeur" de la blockchain qui s'agrandit toutes les 10min en moyenne.
        => le niveau de sécurité dépend du nombre de confirmations d'une transaction, c'est à dire du nombre de blocs créés depuis son intégration à la blockchain, et donc de l'ancienneté de la transaction. 
    Une transaction transmise au réseau et qui n'est pas encore dans un bloc n'a aucune valeur.
    Une transaction incluse dans le dernier bloc est dite avoir "1 confirmation".
    Une transaction incluse dans l'avant-dernier bloc est dite avoir "2 confirmation". etc... Le temps est un allié en matière de sécurité pour la blockchain.
    On considère que 3 transactions est un niveau de sécurité suffisant pour la plupart des tx (donc au bout de 30 minutes d'attente en moyenne). 6 confirmations = très haut. Selon le montant et la criticité de la transaction, on va donc attendre plus ou moins longtemps pour accepter une transaction.
        

    
    
==== En détail
    
    - Premier problème : si tout le monde peut créer des transactions sur le réseau, risque de spam et de saturation (espace disque et bande passante) si quelqu'un s'amuse à créer des milliers de transactions à la seconde.
    On veut donc limiter la vitesse de croissance de la blockchain et décourager le spam, oui mais comment ? 
        
    - Deuxième problème : comme toute monnaie, on a besoin d'émettre de la monnaie pour favoriser sa distribution, son adoption et amener de la liquidité. On veut pouvoir émettre de la monnaie sans autorité centrale.
    => Solution : tout le monde peut émettre de la monnaie. Oui mais on souhaite limiter la création monétaire à un rythme donné autrement elle perdra toute sa valeur.
    
    On va imposer une cadence au réseau : la blockchain va grandir par "blocs" à une cadence moyenne de 10 minutes environ. Chaque bloc pourra contenir 1mo de données (qq milliers de transactions traitées) et donnera lieu en même temps à de la création de nouvelle monnaie. Le fait de créer un bloc s'appelle le minage, sans mineur le réseau serait à l'arrêt : les transactions ne seraient pas traitées et aucune nouvelle monnaie ne serait émise.

    Pour gérer cette double contrainte antinomique (tout le monde peut compléter la blockchain mais pas trop et sans spam, tout le monde peut créer de la monnaie mais pas trop) les cryptomonnaies ont plusieurs approches pour résoudre ce problème. Bitcoin a choisi POW (proof of work).
         
    Pour forcer cette cadence (1 bloc/10min), la création d'un bloc nécessitera de solutionner un problème mathématique nécessitant du temps, de la puissance de calcul et de la chance.
    Chaque bloc devra avoir une entête qui correspond au hash de toutes les transactions de ce bloc, ce hash devra être inférieur à une certaine valeur qui va varier en fonction du temps passé à résoudre le temps précédent. Ainsi le réseau va s'autoréguler et s'adapter automatiquement au nombre de mineurs et à leur puissance de calcul pour faire en sorte qu'un bloc soit trouvé toutes les 10 minutes en moyenne.
    De + le mineur va choisir lui-même les transactions à intégrer dans le bloc parmi la liste des transactions en attente de traitement. Pour inciter le mineur à choisir sa transaction, l'usage est de mettre des frais de quelques millibitcoins. + on met de frais, + le mineur aura intéret à choisir sa transaction (car il en empochera les frais), et donc plus vite sera traitée la transaction. c'est aussi une protection antispam car une transaction sans aucun frais a très peu de chance d'être traitée un jour.
    
    A chaque bloc créé, X nouveaux bitcoins sont créés et redistribués au premier mineur ayant trouvé la solution (au début 50, actuellement 25, mi 2016 12,5 pour limiter l'inflation).
    A chaque bloc créé, les transactions incluses dans ce bloc sont considérées comme exécutées.
    Les blocs s'ajoutent les uns après à la suite des autres  toutes les 10 minutes et forment la blockchain.
    
    Problème : que se passe t-il si 2 mineurs trouvent quasi simultanément des solutions valides ?
    Split de la blockchain, plusieurs blocs se rattachent à un même bloc, on se retrouve avec plusieurs branches.
    => Solution : on considère que la chaine la plus longue est la bonne. Plus le temps passe, plus l'une des 2 branches va être en retard sur l'autre, et plus les mineurs vont être incités à miner la branche la plus longue.
    La branche la plus courte sera invalidée automatiquement et les transactions seront invalidées.
    ==> Il y a donc un risque potentiel de voir sa transaction annulée en cas de split, même si c'est très rare. C'est aussi une attaque potentielle : si qq'un a suffisamment de puissance de calcul, il peut tirer une branche d'un bloc précédent pour tenter d'annuler le dernier bloc et faire du "double spending".

    Solution : le niveau de sécurité dépend du nombre de confirmations.

    Une transaction transmise au réseau et qui n'est pas encore dans un bloc n'a aucune valeur.
    Une transaction incluse dans le dernier bloc est dite avoir "1 confirmation".
    Une transaction incluse dans l'avant-dernier bloc est dite avoir "2 confirmation". etc... plus le temps passe, plus il est difficile de créer une branche pour invalider le bloc dans lequel se trouve la transaction. Etant donné que le mineur malveillant est seul contre tous, plus il s'attaque à un bloc ancien, plus il a besoin de puissance pour recalculer les blocs de retard et devenir la branche la plus longue et donc plus l'attaque sera coûteuse.
    On considère que 3 transactions est un niveau de sécurité suffisant pour la plupart des tx (donc au bout de 30 minutes d'attente en moyenne). 6 confirmations = très haut. Selon le montant et la criticité de la transaction, on va donc attendre plus ou moins longtemps pour accepter une transaction.
    
- qu'est ce qu'un pool de minage ?
    Pour donner un ordre de grandeur, le "hashrate" actuel du réseau est de quasiment 1 milliard de GH/s (sachant qu'un processeur ne produit que quelques MH/s, et qu'une bonne carte graphique produit quelques GH/s, et que du matériel ASIC spécialisé et onéreux produit quelques TH/s) [*] https://blockchain.info/fr/charts/hash-rate
    
    Vu cette énorme puissance, un mineur seul dans son garage a très peu de chance de trouver un bloc, et pourrait travailler dans le vide de nombreuses années sans recevoir aucune récompense en contrepartie. => les mineurs s'associent à plusieurs dans des "pools" pour coordonner leurs calculs, et répartir leurs gains à la hauteur de leur puissance, afin d'assurer une source de revenus constants. Ce phénomène est une potentielle faiblesse du réseau bitcoin car si un pool prenait trop d'importance et atteignait 51% de la puissance de calcul, il pourrait potentiellement dicter sa loi et valider n'importe quelle transaction, ce qui reviendrait à tuer le réseau. [*]https://blockchain.info/pools
    
- contraintes liées à la taille de la blockchain
On a vu que pour s'assurer de la validité d'une transaction, il faut connaître l'intégralité de la blockchain càd 60Go.
Problème : ça fait lourd sur un mobile.
Solution : wallet SPV qui ne va s'intéresser qu'aux entêtes des blocs de la blockchain pour s'assurer de la présence d'une transaction, sans télécharger le bloc entier. Cela est possible grâce à la structure des blocs en arbre de Merkle [*] http://www.e-ducat.fr/bitcoin-et-les-arbres-de-merkle/
Limite : un wallet SPV ne peut pas vérifier que la transaction est valide (= qu'elle est correctement signée), il sait juste que la transaction est présente dans le bloc mais fait confiance au reste du réseau qui l'a accepté vu que la blockchain est suffisamment longue.
=> il est vital pour bitcoin que suffisamment d'utilisateurs utilisent des wallets "full nodes" pour détecter les transactions invalides. [*] https://bitnodes.21.co/
    
Il existe d'autres types de d'attaques potentielles qu'on ne verra pas en détail ici : transaction maleability, autres cas de double spending etc.


////

- mode de développement et d'évolution (BIP, évolutions/forks selon principe de vote des mineurs...)
- débats notamment sur la taille de la blockchain (fork NXT). 


Mesurer ses enjeux
- disruption : suppression des autorités et des intermédiaires : banques, dns, mail, "uberisation d'uber"...
- utilisations monnaie programmable : multisig, smart contracts programmables, héritage, lotterie...
- utilisations blockchain aujourd'hui : bitmessage, preuve (horodatage) sur blockchain... 
- demain : projets en cours (altcoins, ethereum...), investissements, bulle blockchain


Usages dans le monde
- Certification et tracabilité de diamants : http://www.coindesk.com/everledger-blockchain-tech-fight-diamond-theft/
- namecoin : noms de domaines décentralisés

////