= Les causes de l'etat limite / borderline
:hp-tags: santé, solution





== Les causes et facteurs déclencheurs

- Avant la naissance (transmission intra-utérine, mémoire cellulaire)
  * Déprime ou stress de la mère
  * Bébé non désiré

- A la naissance
  * Naissance prématurée : arrachement du bébé à sa mère

- Enfance / adolescence
  * Enfant élevé à la dure : manque de témoignage d'affection de la part des parents
  * Tête de turc : maltraitance à l'école / au collège, non soutenu par les parents ("tu n'as qu'à te défendre")
  * Dévalorisation par les parents ("Quel bon à rien", "Si je meurs qu'est ce que tu vas devenir")
  * Succession d'abus : physiques, sexuels, psychologiques.
  
  
Ces facteurs ne provoquent pas systématiquement de trouble de la personnalité borderline, mais leur cumul et l'âge sont déterminants :

6 ans < très grave < 15-16 ans < grave <  22 ans < moins grave
  
  

== Démographie
La maladie touche autant les femmes que les hommes, mais s'exprime différemment :

- Les femmes auront tendance à retourner leur douleur contre elles-mêmes : scarification, anorexie, etc ("si je sors ma violence je casse tout")
- Les hommes l'expriment sur les autres : violences, cherchent les coups



  
Un enfant victime d'abus aura tendance à se rapprocher inconsciemment de personnes qui vont abuser de lui, notamment des pervers narcissiques.
  
  
Deux borderlines ne s'attirent généralement pas.



== En guérir
Maladie reconnue et classifiée dans DSM4. 
Mais elle est très peu connue en France, peu de professionnels sont formés.

Cette maladie ne peut se soigner sans psychothérapie adaptée. 
Une thérapie adaptée permet d'apprendre à gérer ses émotions au quotidien.






== Symptômes
Pour le malade :

- Peur panique de l'abandon
- Sensation de vide affectif, de ne pas être aimé, chute dans un "puis sans fond"
- Impatience
- Impression de ne pas être compris ou écouté
  
  
Pour son entourage :

- Crises que l'on ne voit pas venir
- L'entourage peut voir le malade comme :
   * Impatient
   * Egoïste ou égocentrique
   * Ayant des réactions disproportionnées pour des détails de la vie courante (ex : si l'on ne répond pas à la seconde à ses sollicitations / ses messages)
- L'entourage en souffre :
   * Sentiment de sauveur envers le malade
   * Sensation d'être manipulé ou culpabilisé
  
  

Douleurs insupportables à l'atterrissage en avion qui se manifestent par :

- mal de tête intense au niveau des yeux, sinus, crâne (sensation d'étau qui se resserre, clou dans l'oeil, implosion/explosion... _céphalée_)
- mal aux oreilles, sinus, pouvant se propager jusque dans la mâchoire
- les douleurs s'estompent peu à peu quelques heures après l'atterrissage.

Peu d'infos à ce sujet sur internet, peu de médecins prennent le problème au sérieux. +


 
    
    
---
Sources :

http://aforpel.org/ +
http://aapel.org