= Douleurs extrêmes à l'atterrissage en avion
:hp-alt-title: douleurs extremes atterrissage avion
:hp-tags: santé, solution

Douleurs insupportables à l'atterrissage en avion qui se manifestent par :

- mal de tête intense au niveau des yeux, sinus, crâne (sensation d'étau qui se resserre, clou dans l'oeil, implosion/explosion... _céphalée_)
- mal aux oreilles, sinus, pouvant se propager jusque dans la mâchoire
- les douleurs s'estompent peu à peu quelques heures après l'atterrissage.

Peu d'infos à ce sujet sur internet, peu de médecins prennent le problème au sérieux. +



== Les causes possibles

- La trompe d'Eustache ne parvient pas à équilibrer la pression interne des poches d'air votre corps (généralement parce que c'est bouché)
- Phénomène très accentué en cas de rhume ou sinusite


== Solution

L'important est de dégager le nez et les sinus avant que la douleur ne se produise.

- Prendre un décongestionnant avant l'atterrissage, par exemple :
	* Le plus efficace, *Derinox* : 2 pulvérisation dans le nez (narine oposée à l'oreille qui vient de se boucher) un peu avant la descente
    * D'autres : Drixoral, nasacort
    
- Bien se moucher et faire un *traitement des sinus avec un spray à base d'eau de mer* quelques jours avant le départ
    
- Autre exemple de traitement cité sur un forum :
    * EXTRANASE : 3 dragées 3 fois par jour pendant les 3 jours qui précèdent le vol
    * KESTINLYO : 1 comprimé par jour pendant les 3 jours qui précèdent le vol
    * RHINOFLUIMUCIL : 2 à 3 pulvérisations dans le nez une heure avant l’atterrissage puis quelques minutes avant l’atterrissage.
    
- Placer une source de chaleur près des oreilles : 
    * _Oreilles de mickey_ : en cas de douleur insupportable, les hotesses peuvent vous préparer des lingettes imbibées d'eau brûlante dans 2 gobelets, à plaquer hermétiquement contre vos oreilles... la chaleur fera son effet. Cela semble très bien fonctionner et c'est particulièrement sexy ;-)
    * En plus discret : emmener 2 chaufferettes à main et les plaquer contre les oreilles
    
- D'autres solutions moins efficaces :
    * Mâcher un chewing gum
    * Se forcer à bâiller
    * Manoeuvre de vasalva : dangereuse pour les tympans, à éviter
    * Le N300, dispositif pour décompresser les oreilles (http://n300.fr) ne semble pas efficace

    
    
    
---
Sources :

http://www.zananas-martinique.com/forums/72552.htm +
http://forum.geekzone.fr/t/mal-au-crane-en-avion/47294/12 +
http://laterresurson31.fr/en-avion-je-mets-des-oreilles-de-mickey/