= Introduction à Bitcoin
:hp-tags: bitcoin

Cet article est une introduction rapide à Bitcoin.


== Bitcoin, c'est quoi ?
C'est quoi :

   * une cryptomonnaie expérimentale = monnaie dématérialisée dont la sécurité est assurée par des principes cryptographiques
   
   * une cryptomonnaie décentralisée = peer to peer sans autorité centrale

   * la 1è cryptomonnaie à connaître un tel succès


Pourquoi c'est intéressant :

* génial d'un point de vue conceptuel et technique (blockchain)

   * comprendre le fonctionnement d'un système décentralisé dont on peut observer le fonctionnement en temps réel (transparent et open-source)

   * disruptif au delà de la simple monnaie : l'approche pour se passer d'autorité centrale et de tiers de confiance est transposable dans de nombreux domaines (on parle d'_uberisation d'Uber_)

   * terreau d'innovations : une nouvelle bulle technologique se forme, de nombreux projets innovants se forment

   * certains considèrent la technologie qu'il utilise (blockchain) comme une révolution
[quote,Nicolas Cary, cofondateur de Blockchain.info]
La technologie Blockchain sera aussi importante pour le monde que l’invention de l’imprimerie par Gutenberg


Créé quand, par qui

   * en novembre 2008, _Satoshi Nakamoto_ (pseudo) publie les spécifications techniques de Bitcoin (white paper :  
   https://bitcoin.org/bitcoin.pdf[bitcoin.pdf])

   * en janvier 2009 Satoshi publie le programme en open-source et le réseau enregistre ses premières transactions notamment avec _Hal Finney_ (dev PGP)

   * en 2010, achat de la 1è pizza en bitcoins (pour 10000 BTC)

   * en décembre 2010, dernier message de Satoshi qui annonce quitter le projet

   * aujourd'hui, après moultes péripéties, Bitcoin est valorisé à 6 milliards de $, est utilisé par ~2 millions d'utilisateurs qui s'échangent 15 millions de bitcoins en circulation, au rythme de > 200,000 transactions (tx) / j


Est-ce une invention nouvelle, est-ce révolutionnaire ?

   * Les cryptomonnaies sont une révolution en soi : elles répondent à un problème informatique jusqu'alors non résolu : on ne savait pas gérer des transferts de propriété (ou de jeton/token) de manière décentralisée. On ne savait pas garantir la propriété d'une ressource à son seul propriétaire sur un réseau décentralisé ouvert.

   * Bitcoin n'est pas la première expérimentation de crypto : digicash (1990), hashcash (1997), bitgold (1998). Mais ces expérimentations n'ont jamais vraiment décollé (problèmes de sécurité, pas assez d'utilisateurs).

   * Le génie de Bitcoin est d'avoir trouvé le cocktail qui a mené à son adoption massive : +
une monnaie qui marche dans la vie de tous les jours et qui combine sécurité et forte incentive qui a permi de rassembler suffisamment d'utilisateurs pour atteindre la masse critique et passer du gadget expérimental à un réel moyen de paiement reconnu et sûr.


Quelles sont les propriétés de Bitcoin ? 

   * 1 unité = 1 BTC, divisible à 8 chiffres après la virgule. 1 Satoshi = 0.00000001 bitcoin
   
   * cappé à 21 millions de bitcoins (production décroissante au fil des ans) => inflation limitée et programmée à l'avance, au contraire de l'euro ou du dollar (dont la production est assurée par une banque centrale)


   * transparent et pseudonyme mais traçable : tout le monde peut savoir tout ce qui se passe sur le réseau, et remonter l'historique des transactions depuis sa création => pseudonyme mais pas anonyme : on sait ce qui s'y passe mais on ne connaît pas l'identité des utilisateurs (des outils facilitent l'analyse forensic : https://www.blockseer.com/g/v9qpi1fO7v3k[blockseer.com] http://www.oxt.me[oxt.me])

   * niveau de sécurité et frais de transaction égaux quel que soit le montant échangé

   * non réversible : aucun moyen d'annuler une transaction => on peut être payé de manière certaine : contrairement à paypal, SEPA, CB qui peuvent être annulés plusieurs mois après en cas de fraude, une transaction Bitcoin confirmée ne peut être annulée

   * programmable : langage de script pour automatiser des transactions complexes (on parle de _monnaie programmable_)


Pour quels usages ?

   * aucune autorité = personne ne peut le controler ou en changer les règles, pour l'arreter il faut arrêter internet => non censurable (utile pour recueillir des dons, cf la fermeture du compte paypal de wikileaks)

   * aucun tiers de confiance : la sécurité des transactions est garantie par des preuves mathématiques et cryptographiques et non par une banque/assurance qui promet de rembourser en cas de pépin => utile aux pays corrompus qui n'ont pas des banques dignes de confiance. Les bitcoins s'échangent déjà en Afrique par sms.


   * pour se faire payer de manière certaine sans avoir à faire confiance à qui que ce soit (émetteur, banque) et à bas coût quelque soit le montant => ventes d'art, de biens maisons/véhicules, etc

   * pour envoyer instantanément de l'argent, en main propre ou à l'autre bout du monde, à moindre frais VS western union. Transaction instantanée VS plusieurs jours pour SEPA 

   * pour payer sur internet : services en ligne (hébergement, noms de domaines, vpn), bars, pizza.fr

   * pour être sa propre banque et rester maitre de son argent : argent disponible partout, tout le temps, sans contrainte (plafond dépense/retrait), sans risque de se faire cambrioler ou de se faire ponctionner son compte en banque en cas de crise économique

   * pour des sites de jeux d'argent, sites de pari (bitbet.com), lotteries en ligne entièrement automatisées et transparentes (dérives : ponzi chinois MMM Global)


